### ISSUE TITLE
📚 Documentation: fix examples markdown files

### ISSUE THREAD

**Issue by OscarRG** [appwrite/sdk-for-go#5]
### 💭 Description

Since we have a go SDK we should fix the examples we have added as samples. By fixing I mean applying a markdown code format or it would also be fine to create a *.go file and list it in a README.md.

Examples currently look like this:

![image](https://user-images.githubusercontent.com/80918302/136746139-a918c43e-065a-43d6-8b87-3f998f52639d.png)

In case the SDK does not work or is under construction, we can edit the README.md

I volunteer to work on this issue. If it's ok you can assign it to me.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by phaus** [comment]
This markdown is generated by https://github.com/appwrite/sdk-generator - the template does not seem to use code blocks at all. I don't know, why this is the case (maybe @eldadfux can explain why).

**Comment by eldadfux** [comment]
The markdown code format is not required. We fetch the examples as is on appwrite.io/docs and parse the examples on the HTML itself.
