### ISSUE TITLE
🐛 Bug Report:  Cannot Install SDK for Go?

### ISSUE THREAD

**Issue by AndrewDonelson** [appwrite/sdk-for-go#6]
### 👟 Reproduction steps

running `go get github.com/appwrite/sdk-for-go`
go version: `go version go1.17 linux/amd64`

I am sure this works - Am I missing something? Something missing from the documentation?

### 👍 Expected behavior

Install the Package(s)

### 👎 Actual Behavior

Output:
```
➜  GWF-Credo git:(migrate-mysql-to-appwrite) ✗ go get github.com/appwrite/sdk-for-go

# github.com/appwrite/sdk-for-go
/home/a****w/go/pkg/mod/github.com/appwrite/sdk-for-go@v0.0.0-20211006123942-afa20940edef/database.go:114:63: undefined: object
/home/a****w/go/pkg/mod/github.com/appwrite/sdk-for-go@v0.0.0-20211006123942-afa20940edef/database.go:143:82: undefined: object
/home/a****w/go/pkg/mod/github.com/appwrite/sdk-for-go@v0.0.0-20211006123942-afa20940edef/users.go:83:52: undefined: object
```

### 🎲 Appwrite version

Version 0.8.x

### 💻 Operating system

Linux

### 🧱 Your Environment

In-House DevOps maintains Ubuntu 20.x Prototype/Dev box

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
This SDK is still a work ing progress.
